---
language: node_js
node_js:
  - "4"
  - "6"
  - "stable"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  - TEST_FRAMEWORK=ember-cli-qunit
  - TEST_FRAMEWORK=ember-cli-mocha
  # we recommend new addons test the current and previous LTS
  # as well as latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

install:
  - ./bin/install-test-framework.sh

script:
  - npm test

after_script:
  - npm run coverage
