language: node_js
node_js:
  - "6"

addons:
  chrome: stable

cache:
  yarn: true

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-canary TEST_FRAMEWORK=ember-cli-mocha

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
        - ./bin/install-test-framework.sh
      script:
        - yarn lint:js
        - yarn test:all

    - name: "Floating Dependencies"
      script:
        - yarn test:all

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.16 TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16 TEST_FRAMEWORK=ember-cli-mocha
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18 TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18 TEST_FRAMEWORK=ember-cli-mocha
    - env: EMBER_TRY_SCENARIO=ember-release TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-release TEST_FRAMEWORK=ember-cli-mocha
    - env: EMBER_TRY_SCENARIO=ember-beta TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-beta TEST_FRAMEWORK=ember-cli-mocha
    - env: EMBER_TRY_SCENARIO=ember-canary TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-canary TEST_FRAMEWORK=ember-cli-mocha
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery TEST_FRAMEWORK=ember-qunit
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery TEST_FRAMEWORK=ember-cli-mocha

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
