name: CI Build

on:
  push:
    branches: [ master, 'v*' ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test:ember

  floating-dependencies:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --no-lockfile
      - run: yarn test:ember

  try-scenarios:
    name: "Try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-default-with-jquery
          - ember-default-with-mocha
          - ember-classic
          - embroider-safe
          - embroider-safe-with-mocha
          - embroider-optimized
          - embroider-optimized-with-mocha
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-release
          - ember-beta
          - ember-canary
          - ember-qunit-4

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
